### ISSUE TITLE
The motion control command in 'stream_motion_test.py' does not work.

### ISSUE THREAD

**Issue by liyipeng2023** [J4nn1K/fanuc-stream-motion#1]
I tried the code in 'stream_motion_test.py' with the roboguide software, and the positions can be correctly obtianed. But the robot does not move as commanded. The returned status of the robot is 4 (which should be 8) after the motion command is sent.

**Comment by chibai** [comment]
I got same problem in ROBOTGUIDE~~Any update for this??

**Comment by liyipeng2023** [comment]
> 
Yes, the problem has been resolved. You may want to see this [j519 issues](https://github.com/ros-industrial/fanuc/issues/247#issuecomment-1554280042)

**Comment by chibai** [comment]
> > 
> 
> Yes, the problem has been resolved. You may want to see this [j519 issues](https://github.com/ros-industrial/fanuc/issues/247#issuecomment-1554280042)

Thank you for reply, is there any script I can test?
